/* SHUNT — daily puzzles.
   GENERATED BY verify.js --emit. Every field below is proven by exhaustive
   search: par is the true minimum slide count to ANY all-words board, and
   sols[] is the complete list of par-length solutions with each one's share
   of all shortest routes. Do not hand-edit; re-run `node verify.js --emit`.
*/
window.SHUNT_PUZZLES = [
  { words:["swim","dive","surf","raft"], start:"swvediufrrfsaitm", par:6,
    sols:[{b:"swimdiveruffarts",pct:62},
          {b:"swimdiverufftsar",pct:15},
          {b:"witsdiveruffmars",pct:15},
          {b:"swimdivesurfraft",pct:8}] },
  { words:["yoga","judo","polo","golf"], start:"gyooadojulpologf", par:6,
    sols:[{b:"yogajudopoolgolf",pct:50},
          {b:"yogajudopologolf",pct:33},
          {b:"yogadojoloopgulf",pct:8},
          {b:"yogajudoloopgolf",pct:8}] },
  { words:["dice","card","chip","coin"], start:"doidcinpaiechcrc", par:6,
    sols:[{b:"cardchipcoindice",pct:41},
          {b:"dicecardchipcoin",pct:41},
          {b:"diedcarpcoinchic",pct:14},
          {b:"diedcarpchicicon",pct:3}] },
  { words:["hawk","dove","crow","wren"], start:"wrwkhavdwroecoen", par:6,
    sols:[{b:"hawkwordcovewren",pct:40},
          {b:"hawkdovecrowwren",pct:20},
          {b:"wrenhawkdovecrow",pct:20},
          {b:"wrenhawkwordcove",pct:20}] },
  { words:["chef","cook","bake","stew"], start:"tfehoekcbokesacw", par:6,
    sols:[{b:"chefcokebakestow",pct:40},
          {b:"feetcokebowshack",pct:40},
          {b:"chefcookbakestew",pct:20}] },
  { words:["glow","dusk","haze","mist"], start:"dliwkhsomaueztgs", par:6,
    sols:[{b:"glowdiskhazemust",pct:50},
          {b:"glowduskhazemist",pct:50}] },
  { words:["quiz","exam","test","grad"], start:"teizgruaqstmexad", par:6,
    sols:[{b:"gradquizexamtest",pct:42},
          {b:"quizexamtestgrad",pct:25},
          {b:"testgradquizexam",pct:17},
          {b:"gradquizseamtext",pct:8},
          {b:"quizseamtextgrad",pct:8}] }
];
